spring.application.name=store
# Porta do servidor (opcional, padrão é 8080)
server.port=8080

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/store_db
spring.datasource.username=admin
spring.datasource.password=2006
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração de logs SQL (opcional)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Timezone (opcional)
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
